server:
  port: 8082
  context-path: '/configuration-manager'
spring:
  application:
    name: configuration-manager
  datasource:
    hikari:
      connection-timeout: 5000
      maximus-pool-size: 2
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/config-manager
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT PROPERTIES.PROP_KEY, PROPERTIES.PROP_VALUE FROM PROPERTIES WHERE APPLICATION=? AND PROFILE=? AND LABEL=?
  properties:
    include: jdbc